name: tbls-gen

on: push

jobs:
  gen:
    name: tbls-gen
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: root
    steps:
      - name: mysql wakeup
        run: |
          until (echo 'SELECT 1' | mysql -h 127.0.0.1 -P 3306 -uroot --silent &> /dev/null); do echo "waiting for mysql to be connectable" && sleep 2; done
      - name: mysql migrate for tbls
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -e "CREATE DATABASE IF NOT EXISTS document DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin"
          sql-migrate up -config=config/dbconfig.yml -env="ci"
      - name: install tbls
        uses: k1low/setup-tbls@2f169dd212c83dae2092297f549c23c5e074e77e # v1.2.0
      - name: run tbls
        run: |
          TBLS_DSN=mysql://root:@localhost:3306/document tbls doc --rm-dist 
